### ISSUE TITLE
`Error: Cannot find module '..'`

### ISSUE THREAD

**Issue by sebn** [konnectors/konitor#50]
```
$ sw_vers -productName
Mac OS X
$ sw_vers -productVersion
10.12.6
$ which node
/usr/local/opt/node@8/bin/node
$ brew info node@8 | grep Cellar
/usr/local/Cellar/node@8/8.9.4 (5,125 files, 49.8MB)
$ which yarn
/usr/local/bin/yarn
$ brew info yarn | grep Cellar
/usr/local/Cellar/yarn/1.3.2 (14 files, 3.9MB) *
$ yarn global add https://github.com/konnectors/konitor.git
$ which konitor
/usr/local/bin/konitor
$ konitor
module.js:540
    throw err;
    ^

Error: Cannot find module '..'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/sebn/.config/yarn/global/node_modules/konitor/bin/konitor.js:5:1)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
$ ~/.config/yarn/global/node_modules/konitor/bin/konitor.js
module.js:540
    throw err;
    ^

Error: Cannot find module '..'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/sebn/.config/yarn/global/node_modules/konitor/bin/konitor.js:5:1)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
```

**Comment by sebn** [comment]
Same after upgrading node to v8.11.1 & yarn to v1.5.1

**Comment by sebn** [comment]
Adding `$(yarn global bin)` to the `PATH` doesn't help. Same on Fedora 27.

**Comment by sebn** [comment]
Got it working on Fedora after uninstalling/reinstalling both node & yarn. Still investigating on macOS.

**Comment by sebn** [comment]
On macOS, after running `yarn global add https://github.com/konnectors/konitor.git`:

```
$ grep main ~/.config/yarn/global/node_modules/konitor/package.json 
  "main": "./dist",
$ ls ~/.config/yarn/global/node_modules/konitor/dist/
ls: /Users/sebn/.config/yarn/global/node_modules/konitor/dist/: No such file or directory
```

While after running `yarn global add konitor`, the `dist` folder is present.
